# coding: utf-8

"""
    Authenticate Platform Account API

    Through this API you can authenticate user credentials and thereby gain access to the available suite of APIs  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: platform-support@authenticateis.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import authenticate_account
from authenticate_account.api.accounts_api import AccountsApi  # noqa: E501
from authenticate_account.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_accounts_forgotten_password_post(self):
        """Test case for api_v1_accounts_forgotten_password_post

        """
        pass

    def test_api_v1_accounts_login_post(self):
        """Test case for api_v1_accounts_login_post

        Logon to the Authenticate platform using credentials of a platform user account  # noqa: E501
        """
        pass

    def test_api_v1_accounts_refresh_token_post(self):
        """Test case for api_v1_accounts_refresh_token_post

        Refresh an expired JWT using a pre-prepared refresh token  # noqa: E501
        """
        pass

    def test_api_v1_accounts_reset_password_post(self):
        """Test case for api_v1_accounts_reset_password_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
